apiVersion: v1 
kind: Service 
metadata: 
  name: movie-recommender-service 
  annotations: 
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb" 
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing" 
spec: 
  selector: 
    app: movie-recommender 
  ports: 
  - port: 8501 
    targetPort: 8501 
    protocol: TCP 
  type: LoadBalancer 
